version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    # build:
    #   context: .
    environment:
      POSTGRES_DB: "dvdrental"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./dvdrental:/dvdrental
      - .db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# python3 -m venv .env
# source .env/bin/activate
# python3 -m pip install --upgrade pip
# pip install dbt-core dbt-postgres
# dbt --version
# dbt ini dbt_webinar
# 
# pg_restore -U postgres -d dvdrental /dvdrental
